#+TITLE: dragon bindings for dired

Have you every needed to drag and drop something but then realised that you have
to open a /shudders/ non emacs file manger? Well no more! This package adds
bindings for [[https://github.com/mwh/dragon][dragon]] so that you can live in emacs a little more!

#+begin_quote
Do note that dired already acts like a sink in normal use so I won't add dragon
functionality for that. its a "why add in an extra step sort of thing"
#+end_quote

** Table of Contense :toc_3:
  - [[#in-file-commands][In file commands]]
  - [[#in-dired-commands][In Dired commands]]
-  [[#installation][Installation]]
  - [[#straight][Straight]]
  - [[#doom][Doom]]
- [[#configuring][Configuring]]
  - [[#variables][Variables]]
  - [[#some-pre-made-configurations][Some pre made configurations]]
    - [[#doom-emacs][Doom emacs]]
    - [[#vanilla][Vanilla]]
- [[#known-bugs][Known Bugs]]
    - [[#the-file-will-not-open-if-there-are-spaces-in-the-name][The file will not open if there are spaces in the name.]]
- [[#contributing][Contributing.]]

** TODO In file commands
these commands are the original work of [[https://github.com/ymarco/][@ymarco]]. Thanks!
They open up a dragon instance for the current file +unless its an org or tex+
+file. then it will check for a corresponding pdf file and drag that instead+
that is still a work in progress. You can still use the command but it will just
drag the current file

At
| Commands                  | use                                                    | flag | requires |
|---------------------------+--------------------------------------------------------+------+----------|
| =:drag=                     | an evil ex command to drag the current buffer and quit | =-x=   | *evil*     |
| ~dired-dragon-current-file~ | a vanilla version of the =:drag= command                 | =-x=   | Nothing  |


** In Dired commands
These commands are meant to be used in dired.
| Commands                | use                                                                            | flag(s) |
|-------------------------+--------------------------------------------------------------------------------+---------|
| ~dired-dragon~            | The Default, drags all and closes after one drop                               | =-x -a=   |
| ~dired-dragon-individual~ | window stays open and you can drag all the files                               |         |
| ~dired-dragon-stay~       | All files will be dropped into the same place but the window will stick around | =-a=      |

*  Installation
** Straight
#+begin_src emacs-lisp
(use-package dired-dragon
  :straight (:host github
             :repo "jeetelongname/dired-dragon"))
#+end_src
** Doom
#+begin_src emacs-lisp
;; packages.el
(package! dired-dragon :recipe (:host github
                                :repo "jeetelongname/dired-dragon"))
;; config.el
(use-package! dired-dragon)
#+end_src

* Configuring
** Variables
if you are on a distro that names dragon differently /cough arch/ then you can change the
variable ~dired-dragon-location~ to the name and or location of your choice
#+begin_src emacs-lisp
(setq dired-dragon-location (executable-find "the name of the executable"))
;; using executable find is a little better as it does not hard code the location
;; but this is optional, just provide it with a full path (eg /usr/bin/dragon)
#+end_src

** Some pre made configurations
*** Doom emacs
if you are a doom emacs user (like me) then this snippet will help
#+begin_src emacs-lisp
;; config.el
(use-package! dired-dragon
  :after dired
  :config
  (map! :map dired-mode-map
        (:prefix "C-d" ;; I don't use `C-d' all to much in dired thus the remap
         :n "d" #'dired-dragon
         :n "s" #'dired-dragon-stay
         :n "i" #'dired-dragon-individual)))
#+end_src

*** Vanilla
this should be a copy and paste affair but I don't use vanilla extensively
#+begin_src emacs-lisp
(use-package dired-dragon
  :straight (:host github
             :repo "jeetelongname/dired-dragon")

  ;; if you use use-package for bindings
  :bind (:map dired-mode-map
         ("C-d d" . dired-dragon)
         ("C-d s" . dired-dragon-stay)
         ("C-d i" . dired-dragon-individual))

  ;; if you don't
  (define-key dired-mode-map (kbd "C-d d") 'dired-dragon)
  (define-key dired-mode-map (kbd "C-d s") 'dired-dragon-stay)
  (define-key dired-mode-map (kbd "C-d i") 'dired-dragon-individual))
#+end_src


* Known Bugs
*** TODO The file will not open if there are spaces in the name.
  yeah this is not ideal and a me issue (not a dragon issue) if this is still
  here then I have forgotten about this entry or its not fixed.

* Contributing.
[[https://github.com/jeetelongname/dired-dragon/issues][Issue's]] are welcome! [[https://github.com/jeetelongname/dired-dragon/pulls][Pull requests]] as well. This is my first "formal" package so
any pointers would be appreciated
